# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'searchResults.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QMainWindow
from webmap import MapWidget
from PyQt5.QtWidgets import QVBoxLayout
from PyQt5.QtCore import QEvent
from RandomImage import random_qpixmap
#from testrun import testcase ""this is for testing purpose""


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1198, 746)
        MainWindow.setStyleSheet("background-color: rgb(228, 250, 251)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.frame = QtWidgets.QFrame(self.widget_2)
        self.frame.setGeometry(QtCore.QRect(-1, 0, 291, 231))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout.addWidget(self.widget_2, 0, 3, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.centralwidget)
        self.widget_6.setObjectName("widget_6")
        self.frameBox_5 = QtWidgets.QFrame(self.widget_6)
        self.frameBox_5.setGeometry(QtCore.QRect(150, 10, 711, 101))
        self.frameBox_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 12px;")
        self.frameBox_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frameBox_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBox_5.setObjectName("frameBox_5")
        self.imageLabel_5 = QtWidgets.QLabel(self.frameBox_5)
        self.imageLabel_5.setGeometry(QtCore.QRect(4, 9, 181, 91))
        self.imageLabel_5.setText("")
        self.imageLabel_5.setObjectName("imageLabel_5")
        self.nameLabel_5 = QtWidgets.QLabel(self.frameBox_5)
        self.nameLabel_5.setGeometry(QtCore.QRect(200, 10, 211, 51))
        self.nameLabel_5.setStyleSheet("font: 75 10pt \"Calibri\";")
        self.nameLabel_5.setText("")
        self.nameLabel_5.setObjectName("nameLabel_5")
        self.addrLabel_5 = QtWidgets.QLabel(self.frameBox_5)
        self.addrLabel_5.setGeometry(QtCore.QRect(200, 60, 451, 31))
        self.addrLabel_5.setStyleSheet("ont: 9pt \"Calibri\";")
        self.addrLabel_5.setText("")
        self.addrLabel_5.setObjectName("addrLabel_5")
        self.categoryLabel_5 = QtWidgets.QLabel(self.frameBox_5)
        self.categoryLabel_5.setGeometry(QtCore.QRect(420, 10, 211, 51))
        self.categoryLabel_5.setStyleSheet("ont: 9pt \"Calibri\";")
        self.categoryLabel_5.setText("")
        self.categoryLabel_5.setObjectName("categoryLabel_5")
        self.frameBox_6 = QtWidgets.QFrame(self.widget_6)
        self.frameBox_6.setGeometry(QtCore.QRect(150, 120, 711, 101))
        self.frameBox_6.setMouseTracking(False)
        self.frameBox_6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 12px;")
        self.frameBox_6.setFrameShape(QtWidgets.QFrame.Box)
        self.frameBox_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBox_6.setObjectName("frameBox_6")
        self.imageLabel_6 = QtWidgets.QLabel(self.frameBox_6)
        self.imageLabel_6.setGeometry(QtCore.QRect(4, 9, 181, 91))
        self.imageLabel_6.setText("")
        self.imageLabel_6.setObjectName("imageLabel_6")
        self.nameLabel_6 = QtWidgets.QLabel(self.frameBox_6)
        self.nameLabel_6.setGeometry(QtCore.QRect(200, 10, 211, 51))
        self.nameLabel_6.setStyleSheet("font: 75 10pt \"Calibri\";")
        self.nameLabel_6.setText("")
        self.nameLabel_6.setObjectName("nameLabel_6")
        self.addrLabel_6 = QtWidgets.QLabel(self.frameBox_6)
        self.addrLabel_6.setGeometry(QtCore.QRect(200, 60, 451, 31))
        self.addrLabel_6.setStyleSheet("ont: 9pt \"Calibri\";")
        self.addrLabel_6.setText("")
        self.addrLabel_6.setObjectName("addrLabel_6")
        self.categoryLabel_6 = QtWidgets.QLabel(self.frameBox_6)
        self.categoryLabel_6.setGeometry(QtCore.QRect(420, 10, 211, 51))
        self.categoryLabel_6.setText("")
        self.categoryLabel_6.setObjectName("categoryLabel_6")
        self.gridLayout.addWidget(self.widget_6, 2, 0, 1, 3)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.frameBox_3 = QtWidgets.QFrame(self.widget)
        self.frameBox_3.setGeometry(QtCore.QRect(150, 10, 711, 101))
        self.frameBox_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 12px;")
        self.frameBox_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frameBox_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBox_3.setObjectName("frameBox_3")
        self.imageLabel_3 = QtWidgets.QLabel(self.frameBox_3)
        self.imageLabel_3.setGeometry(QtCore.QRect(4, 9, 181, 91))
        self.imageLabel_3.setText("")
        self.imageLabel_3.setObjectName("imageLabel_3")
        self.nameLabel_3 = QtWidgets.QLabel(self.frameBox_3)
        self.nameLabel_3.setGeometry(QtCore.QRect(200, 10, 211, 51))
        self.nameLabel_3.setStyleSheet("font: 75 10pt \"Calibri\";")
        self.nameLabel_3.setText("")
        self.nameLabel_3.setObjectName("nameLabel_3")
        self.addrLabel_3 = QtWidgets.QLabel(self.frameBox_3)
        self.addrLabel_3.setGeometry(QtCore.QRect(200, 60, 451, 31))
        self.addrLabel_3.setStyleSheet("ont: 9pt \"Calibri\";")
        self.addrLabel_3.setText("")
        self.addrLabel_3.setObjectName("addrLabel_3")
        self.categoryLabel_3 = QtWidgets.QLabel(self.frameBox_3)
        self.categoryLabel_3.setGeometry(QtCore.QRect(420, 10, 211, 51))
        self.categoryLabel_3.setStyleSheet("ont: 9pt \"Calibri\";")
        self.categoryLabel_3.setText("")
        self.categoryLabel_3.setObjectName("categoryLabel_3")
        self.frameBox_4 = QtWidgets.QFrame(self.widget)
        self.frameBox_4.setGeometry(QtCore.QRect(150, 120, 711, 101))
        self.frameBox_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 12px;")
        self.frameBox_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frameBox_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBox_4.setObjectName("frameBox_4")
        self.imageLabel_4 = QtWidgets.QLabel(self.frameBox_4)
        self.imageLabel_4.setGeometry(QtCore.QRect(4, 9, 181, 91))
        self.imageLabel_4.setText("")
        self.imageLabel_4.setObjectName("imageLabel_4")
        self.nameLabel_4 = QtWidgets.QLabel(self.frameBox_4)
        self.nameLabel_4.setGeometry(QtCore.QRect(200, 10, 211, 51))
        self.nameLabel_4.setStyleSheet("font: 75 10pt \"Calibri\";")
        self.nameLabel_4.setText("")
        self.nameLabel_4.setObjectName("nameLabel_4")
        self.addrLabel_4 = QtWidgets.QLabel(self.frameBox_4)
        self.addrLabel_4.setGeometry(QtCore.QRect(200, 60, 451, 31))
        self.addrLabel_4.setStyleSheet("ont: 9pt \"Calibri\";")
        self.addrLabel_4.setText("")
        self.addrLabel_4.setObjectName("addrLabel_4")
        self.categoryLabel_4 = QtWidgets.QLabel(self.frameBox_4)
        self.categoryLabel_4.setGeometry(QtCore.QRect(420, 10, 211, 51))
        self.categoryLabel_4.setStyleSheet("ont: 9pt \"Calibri\";")
        self.categoryLabel_4.setText("")
        self.categoryLabel_4.setObjectName("categoryLabel_4")
        self.gridLayout.addWidget(self.widget, 1, 0, 1, 3)
        self.widget_4 = QtWidgets.QWidget(self.centralwidget)
        self.widget_4.setObjectName("widget_4")
        self.frameBox_2 = QtWidgets.QFrame(self.widget_4)
        self.frameBox_2.setGeometry(QtCore.QRect(150, 120, 711, 101))
        self.frameBox_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 12px;")
        self.frameBox_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frameBox_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBox_2.setObjectName("frameBox_2")
        self.imageLabel_2 = QtWidgets.QLabel(self.frameBox_2)
        self.imageLabel_2.setGeometry(QtCore.QRect(4, 9, 181, 91))
        self.imageLabel_2.setText("")
        self.imageLabel_2.setObjectName("imageLabel_2")
        self.nameLabel_2 = QtWidgets.QLabel(self.frameBox_2)
        self.nameLabel_2.setGeometry(QtCore.QRect(200, 10, 211, 51))
        self.nameLabel_2.setStyleSheet("font: 75 10pt \"Calibri\";")
        self.nameLabel_2.setText("")
        self.nameLabel_2.setObjectName("nameLabel_2")
        self.addrLabel_2 = QtWidgets.QLabel(self.frameBox_2)
        self.addrLabel_2.setGeometry(QtCore.QRect(200, 60, 451, 31))
        self.addrLabel_2.setStyleSheet("ont: 9pt \"Calibri\";")
        self.addrLabel_2.setText("")
        self.addrLabel_2.setObjectName("addrLabel_2")
        self.categoryLabel_2 = QtWidgets.QLabel(self.frameBox_2)
        self.categoryLabel_2.setGeometry(QtCore.QRect(420, 10, 211, 51))
        self.categoryLabel_2.setStyleSheet("ont: 9pt \"Calibri\";")
        self.categoryLabel_2.setText("")
        self.categoryLabel_2.setObjectName("categoryLabel_2")
        self.framBox = QtWidgets.QFrame(self.widget_4)
        self.framBox.setGeometry(QtCore.QRect(150, 10, 711, 101))
        self.framBox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 12px;")
        self.framBox.setFrameShape(QtWidgets.QFrame.Box)
        self.framBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framBox.setObjectName("framBox")
        self.imageLabel = QtWidgets.QLabel(self.framBox)
        self.imageLabel.setGeometry(QtCore.QRect(4, 9, 181, 91))
        self.imageLabel.setText("")
        self.imageLabel.setObjectName("imageLabel")
        self.nameLabel = QtWidgets.QLabel(self.framBox)
        self.nameLabel.setGeometry(QtCore.QRect(200, 10, 211, 51))
        self.nameLabel.setStyleSheet("font: 75 10pt \"Calibri\";")
        self.nameLabel.setText("")
        self.nameLabel.setObjectName("nameLabel")
        self.addrLabel = QtWidgets.QLabel(self.framBox)
        self.addrLabel.setGeometry(QtCore.QRect(200, 60, 451, 31))
        self.addrLabel.setStyleSheet("ont: 9pt \"Calibri\";")
        self.addrLabel.setText("")
        self.addrLabel.setObjectName("addrLabel")
        self.categoryLabel = QtWidgets.QLabel(self.framBox)
        self.categoryLabel.setGeometry(QtCore.QRect(420, 10, 211, 51))
        self.categoryLabel.setStyleSheet("font: 9pt \"Calibri\";")
        self.categoryLabel.setText("")
        self.categoryLabel.setObjectName("categoryLabel")
        self.gridLayout.addWidget(self.widget_4, 0, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))



class MainWindow(QMainWindow):
    def __init__(self, dict):
        super().__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        
        self.map_widget = MapWidget()
        map_layout = QVBoxLayout(self.ui.frame)
        map_layout.setContentsMargins(0, 0, 0, 0)
        map_layout.addWidget(self.map_widget)
        self.map_widget.load_coordinates(10.775, 106.700, popup_text="Default")

        self.ui.addrLabel.setText(dict[0].addr)
        self.ui.imageLabel.setPixmap(random_qpixmap(dict[0].category))
        self.ui.nameLabel.setText(dict[0].name)
        self.ui.categoryLabel.setText(dict[0].category)

        self.ui.addrLabel_2.setText(dict[1].addr)
        self.ui.imageLabel_2.setPixmap(random_qpixmap(dict[1].category))
        self.ui.nameLabel_2.setText(dict[1].name)
        self.ui.categoryLabel_2.setText(dict[1].category)

        self.ui.addrLabel_3.setText(dict[2].addr)
        self.ui.imageLabel_3.setPixmap(random_qpixmap(dict[2].category))
        self.ui.nameLabel_3.setText(dict[2].name)
        self.ui.categoryLabel_3.setText(dict[2].category)

        self.ui.addrLabel_4.setText(dict[3].addr)
        self.ui.imageLabel_4.setPixmap(random_qpixmap(dict[3].category))
        self.ui.nameLabel_4.setText(dict[3].name)
        self.ui.categoryLabel_4.setText(dict[3].category)

        self.ui.addrLabel_5.setText(dict[4].addr)
        self.ui.imageLabel_5.setPixmap(random_qpixmap(dict[4].category))
        self.ui.nameLabel_5.setText(dict[4].name)
        self.ui.categoryLabel_5.setText(dict[4].category)

        self.ui.addrLabel_6.setText(dict[5].addr)
        self.ui.imageLabel_6.setPixmap(random_qpixmap(dict[5].category))
        self.ui.nameLabel_6.setText(dict[5].name)
        self.ui.categoryLabel_6.setText(dict[5].category)

        self._data = dict

        self._frames = [
            self.ui.framBox,    
            self.ui.frameBox_2,     
            self.ui.frameBox_3,     
            self.ui.frameBox_4,    
            self.ui.frameBox_5,    
            self.ui.frameBox_6,     
        ]

        for frame in self._frames:
            frame.installEventFilter(self)
            frame.setCursor(QtCore.Qt.PointingHandCursor)
            frame.setAttribute(QtCore.Qt.WA_StyledBackground, True)


    def eventFilter(self, obj, event):
        if event.type() == QEvent.MouseButtonPress:
            if obj in self._frames:
                index = self._frames.index(obj)
                item = self._data[index]

                self.map_widget.load_coordinates(
                    item.lat,
                    item.lon,
                    popup_text=item.name
                )
                return True

        return super().eventFilter(obj, event)
