# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'searchQuery.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow
from Categories_Input import Cate, SetCategories
from APIcall_Places import getPlaces
from Input_Classify import cityCheck


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1247, 737)
        MainWindow.setStyleSheet("background-color: rgb(228, 250, 251)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_4 = QtWidgets.QWidget(self.centralwidget)
        self.widget_4.setObjectName("widget_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_3.setGeometry(QtCore.QRect(50, 70, 191, 71))
        self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 16pt \"Calibri\";\n"
"border-radius: 35px")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setMaxLength(169)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton = QtWidgets.QPushButton(self.widget_4)
        self.pushButton.setGeometry(QtCore.QRect(390, 70, 151, 71))
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("font: 75 italic 16pt \"Calibri\";\n"
"background-color: rgb(85, 170, 255)")
        self.pushButton.setAutoDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.widget_4, 0, 2, 1, 2)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(30, 70, 501, 71))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 16pt \"Calibri\";\n"
"border-radius: 35px")
        self.lineEdit.setText("")
        self.lineEdit.setMaxLength(169)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: black;\n"
"    font: 12pt \"Calibri\";\n"
"}\n"
"QPushButton:hover {\n"
"    text-decoration: underline;\n"
"}\n"
"QPushButton:checked {\n"
"    color: gray;\n"
"}")
        self.pushButton_14.setCheckable(True)
        self.pushButton_14.setFlat(True)
        self.pushButton_14.setObjectName("pushButton_14")
        self.verticalLayout_5.addWidget(self.pushButton_14)
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: black;\n"
"    font: 12pt \"Calibri\";\n"
"}\n"
"QPushButton:hover {\n"
"    text-decoration: underline;\n"
"}\n"
"QPushButton:checked {\n"
"    color: gray;\n"
"}")
        self.pushButton_15.setCheckable(True)
        self.pushButton_15.setFlat(True)
        self.pushButton_15.setObjectName("pushButton_15")
        self.verticalLayout_5.addWidget(self.pushButton_15)
        self.gridLayout.addLayout(self.verticalLayout_5, 2, 1, 2, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setStyleSheet("background-color: transparent;\n"
"\n"
"font: 75 20pt \"Calibri\";")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setMinimumSize(QtCore.QSize(30, 40))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_5.setStyleSheet("background-color: transparent;\n"
"\n"
"font: 75 20pt \"Calibri\";")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setMinimumSize(QtCore.QSize(30, 40))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_7.setStyleSheet("background-color: transparent;\n"
"\n"
"font: 75 20pt \"Calibri\";")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setMinimumSize(QtCore.QSize(30, 40))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_8.setStyleSheet("background-color: transparent;\n"
"\n"
"font: 75 20pt \"Calibri\";")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 3, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_20 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_20.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: black;\n"
"    font: 12pt \"Calibri\";\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    color: gray;\n"
"}\n"
"QPushButton:hover {\n"
"    text-decoration: underline;\n"
"}")
        self.pushButton_20.setCheckable(True)
        self.pushButton_20.setFlat(True)
        self.pushButton_20.setObjectName("pushButton_20")
        self.verticalLayout_6.addWidget(self.pushButton_20)
        self.pushButton_21 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_21.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: black;\n"
"    font: 12pt \"Calibri\";\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    color: gray;\n"
"}\n"
"QPushButton:hover {\n"
"    text-decoration: underline;\n"
"}")
        self.pushButton_21.setCheckable(True)
        self.pushButton_21.setFlat(True)
        self.pushButton_21.setObjectName("pushButton_21")
        self.verticalLayout_6.addWidget(self.pushButton_21)
        self.gridLayout.addLayout(self.verticalLayout_6, 2, 0, 2, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton_26 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_26.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: black;\n"
"    font: 12pt \"Calibri\";\n"
"}\n"
"QPushButton:hover {\n"
"    text-decoration: underline;\n"
"}\n"
"QPushButton:checked {\n"
"    color: gray;\n"
"}")
        self.pushButton_26.setCheckable(True)
        self.pushButton_26.setFlat(True)
        self.pushButton_26.setObjectName("pushButton_26")
        self.verticalLayout_7.addWidget(self.pushButton_26)
        self.pushButton_27 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_27.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: black;\n"
"    font: 12pt \"Calibri\";\n"
"}\n"
"QPushButton:hover {\n"
"    text-decoration: underline;\n"
"}\n"
"QPushButton:checked {\n"
"    color: gray;\n"
"}")
        self.pushButton_27.setCheckable(True)
        self.pushButton_27.setFlat(True)
        self.pushButton_27.setObjectName("pushButton_27")
        self.verticalLayout_7.addWidget(self.pushButton_27)
        self.pushButton_28 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_28.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: black;\n"
"    font: 12pt \"Calibri\";\n"
"}\n"
"QPushButton:hover {\n"
"    text-decoration: underline;\n"
"}\n"
"QPushButton:checked {\n"
"    color: gray;\n"
"}")
        self.pushButton_28.setCheckable(False)
        self.pushButton_28.setFlat(True)
        self.pushButton_28.setObjectName("pushButton_28")
        self.verticalLayout_7.addWidget(self.pushButton_28)
        self.pushButton_29 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_29.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: black;\n"
"    font: 12pt \"Calibri\";\n"
"}\n"
"QPushButton:hover {\n"
"    text-decoration: underline;\n"
"}\n"
"QPushButton:checked {\n"
"    color: gray;\n"
"}")
        self.pushButton_29.setCheckable(True)
        self.pushButton_29.setFlat(True)
        self.pushButton_29.setObjectName("pushButton_29")
        self.verticalLayout_7.addWidget(self.pushButton_29)
        self.pushButton_30 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_30.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: black;\n"
"    font: 12pt \"Calibri\";\n"
"}\n"
"QPushButton:hover {\n"
"    text-decoration: underline;\n"
"}\n"
"QPushButton:checked {\n"
"    color: gray;\n"
"}")
        self.pushButton_30.setCheckable(True)
        self.pushButton_30.setFlat(True)
        self.pushButton_30.setObjectName("pushButton_30")
        self.verticalLayout_7.addWidget(self.pushButton_30)
        self.pushButton_31 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_31.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: black;\n"
"    font: 12pt \"Calibri\";\n"
"}\n"
"QPushButton:hover {\n"
"    text-decoration: underline;\n"
"}\n"
"QPushButton:checked {\n"
"    color: gray;\n"
"}")
        self.pushButton_31.setCheckable(True)
        self.pushButton_31.setFlat(True)
        self.pushButton_31.setObjectName("pushButton_31")
        self.verticalLayout_7.addWidget(self.pushButton_31)
        self.gridLayout.addLayout(self.verticalLayout_7, 2, 2, 2, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: black;\n"
"    font: 12pt \"Calibri\";\n"
"}\n"
"QPushButton:hover {\n"
"    text-decoration: underline;\n"
"}\n"
"QPushButton:checked {\n"
"    color: gray;\n"
"}")
        self.pushButton_16.setCheckable(True)
        self.pushButton_16.setFlat(True)
        self.pushButton_16.setObjectName("pushButton_16")
        self.verticalLayout_8.addWidget(self.pushButton_16)
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_17.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: black;\n"
"    font: 12pt \"Calibri\";\n"
"}\n"
"QPushButton:hover {\n"
"    text-decoration: underline;\n"
"}\n"
"QPushButton:checked {\n"
"    color: gray;\n"
"}")
        self.pushButton_17.setCheckable(True)
        self.pushButton_17.setFlat(True)
        self.pushButton_17.setObjectName("pushButton_17")
        self.verticalLayout_8.addWidget(self.pushButton_17)
        self.pushButton_18 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_18.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: black;\n"
"    font: 12pt \"Calibri\";\n"
"}\n"
"QPushButton:hover {\n"
"    text-decoration: underline;\n"
"}\n"
"QPushButton:checked {\n"
"    color: gray;\n"
"}")
        self.pushButton_18.setCheckable(True)
        self.pushButton_18.setFlat(True)
        self.pushButton_18.setObjectName("pushButton_18")
        self.verticalLayout_8.addWidget(self.pushButton_18)
        self.gridLayout.addLayout(self.verticalLayout_8, 2, 3, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Radius (meters)"))
        self.pushButton.setText(_translate("MainWindow", "Suggest"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "The City Where You Wanna Look Up"))
        self.pushButton_14.setText(_translate("MainWindow", "Hotel"))
        self.pushButton_15.setText(_translate("MainWindow", "Motel"))
        self.label_6.setText(_translate("MainWindow", "Commercial"))
        self.label_5.setText(_translate("MainWindow", "Accommodation"))
        self.label_7.setText(_translate("MainWindow", "Entertainment"))
        self.label_8.setText(_translate("MainWindow", "Catering"))
        self.pushButton_20.setText(_translate("MainWindow", "Supermarket"))
        self.pushButton_21.setText(_translate("MainWindow", "Market"))
        self.pushButton_26.setText(_translate("MainWindow", "Culture"))
        self.pushButton_27.setText(_translate("MainWindow", "Cinema"))
        self.pushButton_28.setText(_translate("MainWindow", "Aquarium"))
        self.pushButton_29.setText(_translate("MainWindow", "Theme_Park"))
        self.pushButton_30.setText(_translate("MainWindow", "Water_Park"))
        self.pushButton_31.setText(_translate("MainWindow", "Zoo"))
        self.pushButton_16.setText(_translate("MainWindow", "Restaurant"))
        self.pushButton_17.setText(_translate("MainWindow", "Cafe"))
        self.pushButton_18.setText(_translate("MainWindow", "Bar"))

class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)

        self.CateQuery = Cate
        self.buttons = [
                self.ui.pushButton_14,  # Hotel
                self.ui.pushButton_15,  # Motel
                self.ui.pushButton_20,  # Supermarket
                self.ui.pushButton_21,  # Market
                self.ui.pushButton_26,  # Culture
                self.ui.pushButton_27,  # Cinema
                self.ui.pushButton_28,  # Aquarium
                self.ui.pushButton_29,  # Theme_Park
                self.ui.pushButton_30,  # Water_Park
                self.ui.pushButton_31,  # Zoo
                self.ui.pushButton_16,  # Restaurant
                self.ui.pushButton_17,  # Cafe
                self.ui.pushButton_18,  # Bar
        ]
        for btn in self.buttons:
            btn.toggled.connect(self.updateCateQuery)
        
        self.ui.pushButton.clicked.connect(self.onSuggestion)

    def updateCateQuery(self):
        btn = self.sender()
        if btn is None:
                return

        btn_text = btn.text()
        checked = btn.isChecked()

        for category, items in self.CateQuery.items():
                if btn_text in items:
                        self.CateQuery[category][btn_text] = checked
                        break

    def onSuggestion(self):
        lat, lon = cityCheck(self.ui.lineEdit.text().strip())
        resultList = getPlaces(lat, lon, self.ui.lineEdit_3.text(), SetCategories(self.CateQuery))
        # Close this window
        # Initialize searchResults' MainWindow: 
        # a = searchResults.MainWindow(resultList) ...

