# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 699)
        MainWindow.setStyleSheet("#centralwidget {\n"
"    border-image: url(:/Login/background.jpg) 0 0 0 0 stretch stretch;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 146, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 67, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(182, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(182, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 2, 2, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(400, 450))
        self.frame.setMaximumSize(QtCore.QSize(400, 450))
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: #fdfbf7; /* Màu trắng ngà/kem */\n"
"    border-radius: 20px;\n"
"    border: 1px solid #dcdde1;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.lblLogo = QtWidgets.QLabel(self.frame)
        self.lblLogo.setMinimumSize(QtCore.QSize(60, 60))
        self.lblLogo.setMaximumSize(QtCore.QSize(50, 50))
        self.lblLogo.setStyleSheet("")
        self.lblLogo.setText("")
        self.lblLogo.setPixmap(QtGui.QPixmap(":/Login/logo.png"))
        self.lblLogo.setScaledContents(True)
        self.lblLogo.setAlignment(QtCore.Qt.AlignCenter)
        self.lblLogo.setObjectName("lblLogo")
        self.horizontalLayout_2.addWidget(self.lblLogo)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.lblTitle = QtWidgets.QLabel(self.frame)
        self.lblTitle.setStyleSheet("QLabel#lblTitle {\n"
"    border: none;\n"
"    font-size: 15px;           /* Chữ to rõ */\n"
"    font-weight: bold;         /* In đậm */\n"
"    color: #2c3e50;            /* Màu xanh đen sang trọng */\n"
"    font-family: \"Segoe UI\";   /* Font hiện đại (có thể đổi thành Arial) */\n"
"    margin-bottom: 20px;       /* Tạo khoảng cách với ô Username bên dưới */\n"
"}\n"
"")
        self.lblTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout.addWidget(self.lblTitle)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(44, -1, 44, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.usernameINPUT = QtWidgets.QLineEdit(self.frame)
        self.usernameINPUT.setMinimumSize(QtCore.QSize(200, 20))
        self.usernameINPUT.setBaseSize(QtCore.QSize(180, 20))
        self.usernameINPUT.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #555555; /* Viền màu xám, dày 2px */\n"
"    border-radius: 10px;       /* Độ bo tròn (số càng lớn càng tròn) */\n"
"    padding-left: 10px;        /* Đệm trái để chữ không sát mép */\n"
"    padding-right: 10px;       /* Đệm phải */\n"
"    background-color:  #e0ffff ; /* Màu nền */\n"
"    color: black;              /* Màu chữ */\n"
"    padding: 12px;\n"
"\n"
"}\n"
"\n"
"/* Hiệu ứng khi bấm chuột vào */\n"
"QLineEdit:focus {\n"
"    border: 1px solid #00aaff; /* Đổi màu viền sang xanh dương */\n"
"}\n"
"\n"
"")
        self.usernameINPUT.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.usernameINPUT.setPlaceholderText("Username")
        self.usernameINPUT.setObjectName("usernameINPUT")
        self.horizontalLayout_5.addWidget(self.usernameINPUT)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    border: none;    \n"
"    margin-top: 0px; \n"
"}")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.paswordINPUT = QtWidgets.QLineEdit(self.groupBox)
        self.paswordINPUT.setMinimumSize(QtCore.QSize(200, 20))
        self.paswordINPUT.setBaseSize(QtCore.QSize(180, 20))
        self.paswordINPUT.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #555555; /* Viền màu xám, dày 2px */\n"
"    border-radius: 10px;       /* Độ bo tròn (số càng lớn càng tròn) */\n"
"    padding-left: 10px;        /* Đệm trái để chữ không sát mép */\n"
"    padding-right: 10px;       /* Đệm phải */\n"
"    background-color:  #e0ffff ; /* Màu nền */\n"
"    color: black;              /* Màu chữ */\n"
"    padding: 12px;\n"
"    margin-left: 34px;\n"
"}\n"
"\n"
"/* Hiệu ứng khi bấm chuột vào */\n"
"QLineEdit:focus {\n"
"    border: 1px solid #00aaff; /* Đổi màu viền sang xanh dương */\n"
"}\n"
"\n"
"QLineEdit::placeholderText{\n"
"    color: #000000;\n"
"    front-style: italic;\n"
"    font-weight: normal;\n"
"}")
        self.paswordINPUT.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.paswordINPUT.setPlaceholderText("Password")
        self.paswordINPUT.setObjectName("paswordINPUT")
        self.horizontalLayout.addWidget(self.paswordINPUT)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: transparent; /* Nền trong suốt */\n"
"    border: none;                  /* Không viền */\n"
"    font-size: 20px;               /* Chữ to ra cho dễ bấm */\n"
"    color: #3498db;                /* Màu xanh */\n"
"}\n"
"QPushButton:hover {\n"
"    color: #2980b9;                /* Đổi màu khi di chuột */\n"
"}")
        self.pushButton.setCheckable(True)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setStyleSheet("/* Trạng thái bình thường: Trong suốt, không viền */\n"
"QLabel {\n"
"    background-color: transparent; /* Nền trong suốt */\n"
"    border: none;                  /* Bỏ viền */\n"
"    color: #d3d3d3;                /* Màu xanh link (giống web) */\n"
"    font-size: 14px;\n"
"    text-align: left;              /* Canh trái (hoặc center tùy bạn) */\n"
"}\n"
"")
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setStyleSheet("/* Trạng thái bình thường: Trong suốt, không viền */\n"
"QPushButton {\n"
"    background-color: transparent; /* Nền trong suốt */\n"
"    border: none;                  /* Bỏ viền */\n"
"    color: #3498db;                /* Màu xanh link (giống web) */\n"
"    font-size: 14px;\n"
"    text-align: left;              /* Canh trái (hoặc center tùy bạn) */\n"
"}\n"
"\n"
"/* Khi di chuột vào: Gạch chân và đổi màu đậm hơn */\n"
"QPushButton:hover {\n"
"    color: #1d72b8;                /* Xanh đậm hơn */\n"
"    text-decoration: underline;    /* Gạch chân (đây là mấu chốt) */\n"
"}\n"
"\n"
"/* Khi bấm xuống */\n"
"QPushButton:pressed {\n"
"    color: #155a8a;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(100, -1, 100, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.loginBUTTON = QtWidgets.QPushButton(self.frame)
        self.loginBUTTON.setMinimumSize(QtCore.QSize(80, 20))
        self.loginBUTTON.setStyleSheet("/* --- TRẠNG THÁI BÌNH THƯỜNG --- */\n"
"QPushButton {\n"
"    background-color: #2980b9; /* Màu xanh dương (Màu nền chính) */\n"
"    color: white;              /* Màu chữ */\n"
"    font-weight: bold;         /* Chữ đậm */\n"
"    font-size: 8px;           /* Cỡ chữ */\n"
"    border-radius: 10px;       /* Bo tròn góc */\n"
"    padding: 10px;             /* Khoảng cách đệm để nút to ra */\n"
"    border: none;              /* Xóa viền xấu xí mặc định */\n"
"    margin-top: 8px;\n"
"    margin-bottom: 20px;\n"
"}\n"
"\n"
"/* --- KHI DI CHUỘT VÀO (HOVER) --- */\n"
"QPushButton:hover {\n"
"    background-color: #3498db; /* Đổi sang màu xanh sáng hơn */\n"
"}\n"
"\n"
"/* --- KHI BẤM GIỮ CHUỘT (PRESSED) --- */\n"
"QPushButton:pressed {\n"
"    background-color: #1f618d; /* Đổi sang màu tối hơn (cảm giác nút lún xuống) */\n"
"    padding-top: 12px;         /* (Mẹo) Dịch chữ xuống 1 xíu tạo cảm giác nhấn thật */\n"
"    padding-left: 12px;\n"
"}")
        self.loginBUTTON.setObjectName("loginBUTTON")
        self.horizontalLayout_4.addWidget(self.loginBUTTON)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.gridLayout.addWidget(self.frame, 1, 1, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblTitle.setText(_translate("MainWindow", "LOGIN TO YOUR ACCOUNT"))
        self.pushButton.setText(_translate("MainWindow", "👁"))
        self.label.setText(_translate("MainWindow", "Don\'t have ann account yet? Create one"))
        self.pushButton_2.setText(_translate("MainWindow", "here"))
        self.loginBUTTON.setText(_translate("MainWindow", "Login"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
